name: Update APK link in README

on:
  release:
    types: [published]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest APK URL
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const release = context.payload.release;
            const apk = release.assets.find(a => a.name.endsWith('.apk'));
            core.setOutput("url", apk.browser_download_url);

      - name: Replace APK link in README
        run: |
          sed -i "s|https://github.com/RahulSahana/my_calculator/releases/download/.*/.*\.apk|${{ steps.get_release.outputs.url }}|g" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Updated APK link to latest version" || echo "No changes"
          git push
